name: Check SSL Expiry

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check_ssl_expiry:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOMAINS_FILE: domains.txt

    steps:
      - uses: actions/checkout@v2
      - name: Check SSL Expiry
        run: |
          python check_ssl_expiry.py
      - name: Send Slack Notification
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{
            "text": "SSL Expiry Alert",
            "attachments": [
              {
                "title": "Domain",
                "value": "${{ steps.check_ssl_expiry.outputs.domain }}",
                "short": false
              },
              {
                "title": "Warning",
                "value": "${{ steps.check_ssl_expiry.outputs.warning }}",
                "short": false
              }
            ]
          }' "${SLACK_WEBHOOK_URL}"
