name: Check SSL Expiry

on:
  schedule:
    #- cron: '0 0 * * *'
      workflow_dispatch:

jobs:
  check_ssl_expiry:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOMAINS_FILE: domains.txt

    steps:
      - uses: actions/checkout@v2
      - name: Execute Python Script and Send Slack Notification
        run: |
          output=$(python check_ssl_expiry.py)
          curl -X POST -H 'Content-Type: application/json' -d "{
            \"text\": \"$output\"
          }" "${SLACK_WEBHOOK_URL}"
